In [3]:
# panda is alibrary to handle file in table like structre or db related files and function of this panda library will be saved in this memory
# created the alias for panda as pd in code we will use pd instead of panda for shortcut
import pandas as pd

In [4]:
#The read_csv is a method or function of pandas which will read the specified file and store the data in variable dataset
# As part of Modle Creation and learning we have done the data collection and preprocessing as this data is preprocessed data
dataset = pd.read_csv("Salary_Data.csv")

In [10]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
# store the input of the table in varaible, independent is input data so store the tab YearsExperience of dataset to independent
# As part of Modle Creation and learning procedure the sp%lit of input and output this step split the input split
independent = dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [6]:
# store the output of the table in varaible, dependent is output data so store the tab Salary of dataset to independent
# As part of Modle Creation and learning procedure the split of input and output this step split the output split
dependent = dataset[["Salary"]]
dependent

    Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [7]:
# This sklearn is a library and has class model_selection and tran_test_split is a method or function specifically used to split the train and test data split
# As part of Modle Creation and learning procedure the split of train and test data is done
# it generate 4 different data, from input data it generate the train and test date and from out[ut data it generate train and test data 
#here x_ is input data and y_ is output data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0 )

In [13]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [15]:
# the regressor.coef_ is function used to calculate the slope regressor is the model that we created and coef_ is function that calculates the weight/slope
# weight is a slope in which pattern the data varies
weight = regressor.coef_
weight

array([[9360.26128619]])

In [16]:
# the regressor.intercept_ is function used to calculate the intercept. regressor is the model that we created and intercept_ is function that calculates the intercepts
# intercept_ is a function o
bias = regressor.intercept_
bias

array([26777.3913412])

In [17]:
# regressor.predict is the functiom used to predict the output based on the x_test data and y_test is the actual data
#use to cross check the prediction
y_pred = regressor.predict(x_test)

In [18]:
# sklearn.metric is library and r2.score is function used to create the metrics which will calculate the accuracy of the prediction 
# with the y_test which is actual test data and y_pred is the predicted data
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [19]:
# r_score is close to learn then the model is good
r_score

0.9740993407213511

In [20]:
# import pickle is a library to save the model
# provide file name in which the model can be saved the model the extention of file should ve sav for pickle format
import pickle
filename = "finalized_model_linear.sav"

In [21]:
#pickle.dum() is a method to save the created model into the specific file in our local system
pickle.dump(regressor, open(filename, 'wb'))

In [26]:
# how to load the saved model the pickle.load() is used to opne the model with file name mentioned in to the loaded_model
#the result variable is used to store the prediction with input mention into the parameter
loaded_model = pickle.load(open("finalized_model_linear.sav", 'rb'))
result=loaded_model.predict([[5]])

C:\Users\I308878\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [27]:
result

array([[73578.69777217]])